services:
  version: "3.8"

services:
  db:
    image: mongo:4.4.14-focal
    restart: always
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: retroadmin
      MONGO_INITDB_ROOT_PASSWORD: reviewsadmin
  server:
    build: ./server
    command: npm run dev
    volumes:
      - ./server:/code
      - /code/node_modules
    ports:
      - "4000:4000"
    environment:
      - MONGO_NAME=retroreviews
      - MONGO_USER=retroadmin
      - MONGO_PASSWORD=reviewsadmin
      - MONGODB_URL=mongodb://retroadmin:reviewsadmin@mongo:27017/
      - PORT=4000
    depends_on:
      - db
  client:
    build: ./client
    command: npm run dev
    volumes:
      - ./client:/code
      - /code/node_modules
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=4000
      - API_URL=http://localhost:4000/api/
    depends_on:
      - server


